"""create leader_contacts table and remove contact fields from leaders

Revision ID: 1c5ea8f384b1
Revises: fad3d8ca2b12
Create Date: 2026-03-10 18:13:17.144553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5ea8f384b1'
down_revision: Union[str, None] = 'fad3d8ca2b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leader_contacts_leader_id', 'leader_contacts', ['leader_id'], unique=False)
    op.drop_column('gc_leaders', 'is_primary')
    op.drop_column('leaders', 'instagram')
    op.drop_column('leaders', 'whatsapp')
    op.drop_column('leaders', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaders', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leaders', sa.Column('whatsapp', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('leaders', sa.Column('instagram', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('gc_leaders', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_leader_contacts_leader_id', table_name='leader_contacts')
    op.drop_table('leader_contacts')
    # ### end Alembic commands ###
