"""add display_name to leaders and create leader_contacts table

Revision ID: 6035bd9163df
Revises: 1c5ea8f384b1
Create Date: 2026-03-10 18:39:57.429955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6035bd9163df'
down_revision: Union[str, None] = '1c5ea8f384b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaders', sa.Column('display_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaders', 'display_name')
    # ### end Alembic commands ###
